# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_code', models.CharField(blank=True, max_length=15, null=True)),
                ('yearid', models.CharField(blank=True, max_length=15, null=True)),
                ('stint', models.CharField(blank=True, max_length=15, null=True)),
                ('teamid', models.CharField(blank=True, max_length=5, null=True)),
                ('lg', models.CharField(blank=True, max_length=15, null=True)),
                ('g', models.CharField(blank=True, max_length=15, null=True)),
                ('ab', models.CharField(blank=True, max_length=15, null=True)),
                ('r', models.CharField(blank=True, max_length=15, null=True)),
                ('h', models.CharField(blank=True, max_length=15, null=True)),
                ('doubles', models.CharField(blank=True, max_length=15, null=True)),
                ('triples', models.CharField(blank=True, max_length=15, null=True)),
                ('hr', models.CharField(blank=True, max_length=15, null=True)),
                ('rbi', models.CharField(blank=True, max_length=15, null=True)),
                ('sb', models.CharField(blank=True, max_length=15, null=True)),
                ('cs', models.CharField(blank=True, max_length=15, null=True)),
                ('bb', models.CharField(blank=True, max_length=15, null=True)),
                ('so', models.CharField(blank=True, max_length=15, null=True)),
                ('ibb', models.CharField(blank=True, max_length=15, null=True)),
                ('hbp', models.CharField(blank=True, max_length=15, null=True)),
                ('sh', models.CharField(blank=True, max_length=15, null=True)),
                ('sf', models.CharField(blank=True, max_length=15, null=True)),
                ('gidp', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(blank=True, max_length=15, null=True)),
                ('birthYear', models.CharField(blank=True, max_length=15, null=True)),
                ('birthMonth', models.CharField(blank=True, max_length=15, null=True)),
                ('birthDay', models.CharField(blank=True, max_length=15, null=True)),
                ('birthCountry', models.CharField(blank=True, max_length=30, null=True)),
                ('birthState', models.CharField(blank=True, max_length=30, null=True)),
                ('birthCity', models.CharField(blank=True, max_length=30, null=True)),
                ('deathYear', models.CharField(blank=True, max_length=15, null=True)),
                ('deathMonth', models.CharField(blank=True, max_length=15, null=True)),
                ('deathDay', models.CharField(blank=True, max_length=15, null=True)),
                ('deathCountry', models.CharField(blank=True, max_length=30, null=True)),
                ('deathState', models.CharField(blank=True, max_length=30, null=True)),
                ('deathCity', models.CharField(blank=True, max_length=30, null=True)),
                ('nameFirst', models.CharField(blank=True, max_length=25, null=True)),
                ('nameLast', models.CharField(blank=True, max_length=25, null=True)),
                ('nameGiven', models.CharField(blank=True, max_length=40, null=True)),
                ('weight', models.CharField(blank=True, max_length=15, null=True)),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('bats', models.CharField(blank=True, max_length=1, null=True)),
                ('throws', models.CharField(blank=True, max_length=1, null=True)),
                ('debut', models.CharField(blank=True, max_length=15, null=True)),
                ('finalGame', models.CharField(blank=True, max_length=15, null=True)),
                ('retroID', models.CharField(blank=True, max_length=20, null=True)),
                ('bbrefID', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='batting_record',
            name='playerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseballStats.Master'),
        ),
    ]
