# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0002_auto_20161030_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting_record',
            name='master',
        ),
        migrations.RemoveField(
            model_name='fielding_record',
            name='master',
        ),
        migrations.RemoveField(
            model_name='pitching_record',
            name='master',
        ),
        migrations.AlterField(
            model_name='batting_record',
            name='playerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BaseballStats.Master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fielding_record',
            name='playerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BaseballStats.Master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pitching_record',
            name='playerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BaseballStats.Master'),
            preserve_default=False,
        ),
    ]
