# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:54
from __future__ import unicode_literals

from django.db import migrations


import csv


def add_file(apps, schema_editor):
    Master = apps.get_model("BaseballStats", "Master")
    with open('Master.csv') as infile:
        reader = csv.DictReader(infile, delimiter=',', fieldnames=["id", "player_code", "birthYear", "birthMonth",
                                "birthDay", "birthCountry", "birthState", "birthCity", "deathYear", "deathMonth",
                                                                   "deathDay", "deathCountry", "deathState",
                                                                   "deathCity", "nameFirst", "nameLast",
                                                                   "nameGiven", "weight",
                                                                   "height", "bats", "throws",
                                                                   "debut", "finalGame", "retroID", "bbrefID"])
        for row in reader:
            Master.objects.create(player_code=row["player_code"],
                                  birthYear=row["birthYear"], birthMonth=row["birthMonth"],
                                  birthDay=row["birthDay"], birthCountry=row["birthCountry"],
                                  birthState=row["birthState"],
                                  birthCity=row["birthCity"], deathYear=row["deathYear"],
                                  deathMonth=row["deathMonth"], deathDay=row["deathDay"],
                                  deathCountry=row["deathCountry"],
                                  deathState=row["deathState"], deathCity=row["deathCity"], nameFirst=row["nameFirst"],
                                  nameLast=row["nameLast"], nameGiven=row["nameGiven"], weight=row["weight"],
                                  height=row["height"], bats=row["bats"], throws=row["throws"],
                                  debut=row["debut"], finalGame=row["finalGame"], retroID=row["retroID"],
                                  bbrefID=row["bbrefID"])
        raise Exception('HOORAH')


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0003_auto_20161027_0200'),
    ]

    operations = [
        migrations.RunPython(add_file)
    ]
