# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0004_auto_20161027_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_code', models.CharField(blank=True, max_length=15, null=True)),
                ('yearID', models.CharField(blank=True, max_length=15, null=True)),
                ('stint', models.CharField(blank=True, max_length=15, null=True)),
                ('teamID', models.CharField(blank=True, max_length=5, null=True)),
                ('lgID', models.CharField(blank=True, max_length=15, null=True)),
                ('G', models.CharField(blank=True, max_length=15, null=True)),
                ('AB', models.CharField(blank=True, max_length=15, null=True)),
                ('R', models.CharField(blank=True, max_length=15, null=True)),
                ('H', models.CharField(blank=True, max_length=15, null=True)),
                ('Doubles', models.CharField(blank=True, max_length=15, null=True)),
                ('Triples', models.CharField(blank=True, max_length=15, null=True)),
                ('HR', models.CharField(blank=True, max_length=15, null=True)),
                ('RBI', models.CharField(blank=True, max_length=15, null=True)),
                ('SB', models.CharField(blank=True, max_length=15, null=True)),
                ('CS', models.CharField(blank=True, max_length=15, null=True)),
                ('BB', models.CharField(blank=True, max_length=15, null=True)),
                ('SO', models.CharField(blank=True, max_length=15, null=True)),
                ('IBB', models.CharField(blank=True, max_length=15, null=True)),
                ('HBP', models.CharField(blank=True, max_length=15, null=True)),
                ('SH', models.CharField(blank=True, max_length=15, null=True)),
                ('SF', models.CharField(blank=True, max_length=15, null=True)),
                ('GIDP', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='master',
            old_name='player_code',
            new_name='player',
        ),
        migrations.AddField(
            model_name='batting_record',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseballStats.Master'),
        ),
    ]
