# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0006_auto_20161027_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting_record',
            old_name='AB',
            new_name='ab',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='BB',
            new_name='bb',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='CS',
            new_name='cs',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='Doubles',
            new_name='doubles',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='G',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='GIDP',
            new_name='gidp',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='H',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='HBP',
            new_name='hbp',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='HR',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='IBB',
            new_name='ibb',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='R',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='RBI',
            new_name='rbi',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='SB',
            new_name='sb',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='SF',
            new_name='sf',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='SH',
            new_name='sh',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='SO',
            new_name='so',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='Triples',
            new_name='triples',
        ),
    ]
