# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0007_auto_20161027_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting_record',
            old_name='lgID',
            new_name='lg',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='teamID',
            new_name='teamid',
        ),
        migrations.RenameField(
            model_name='batting_record',
            old_name='yearID',
            new_name='yearid',
        ),
    ]
