# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStats', '0009_auto_20161027_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting_record',
            old_name='player',
            new_name='playerid',
        ),
    ]
